/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AdminRouteRouteImport } from "./routes/admin/route"
import { Route as CustomerRouteRouteImport } from "./routes/customer/route"
import { Route as MerchantRouteRouteImport } from "./routes/merchant/route"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register"
import { Route as AdminDashboardRouteImport } from "./routes/admin/dashboard"
import { Route as CustomerCartRouteImport } from "./routes/customer/cart"
import { Route as CustomerHomeRouteImport } from "./routes/customer/home"
import { Route as CustomerProfileRouteImport } from "./routes/customer/profile"
import { Route as MerchantDashboardRouteImport } from "./routes/merchant/dashboard"
import { Route as MerchantMenuRouteImport } from "./routes/merchant/menu"
import { Route as MerchantProfileRouteImport } from "./routes/merchant/profile"
import { Route as MerchantRestaurantRouteImport } from "./routes/merchant/restaurant"
import { Route as AdminOrdersIndexRouteImport } from "./routes/admin/orders/index"
import { Route as AdminOrdersOrderIdRouteImport } from "./routes/admin/orders/$orderId"
import { Route as AdminRestrosIndexRouteImport } from "./routes/admin/restros/index"
import { Route as AdminRestrosRestroIdRouteImport } from "./routes/admin/restros/$restroId"
import { Route as AdminUsersIndexRouteImport } from "./routes/admin/users/index"
import { Route as AdminUsersUserIdRouteImport } from "./routes/admin/users/$userId"
import { Route as CustomerOrdersIndexRouteImport } from "./routes/customer/orders/index"
import { Route as CustomerOrdersOrderIdRouteImport } from "./routes/customer/orders/$orderId"
import { Route as CustomerRestroRestroIdRouteImport } from "./routes/customer/restro.$restroId"
import { Route as MerchantOrdersIndexRouteImport } from "./routes/merchant/orders/index"
import { Route as MerchantOrdersOrderIdRouteImport } from "./routes/merchant/orders/$orderId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
})
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
})
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
})
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: "/customer",
  path: "/customer",
  getParentRoute: () => rootRouteImport,
})
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: "/merchant",
  path: "/merchant",
  getParentRoute: () => rootRouteImport,
})
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
})
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
})
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AdminRouteRoute,
})
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => CustomerRouteRoute,
})
const CustomerHomeRoute = CustomerHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => CustomerRouteRoute,
})
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => CustomerRouteRoute,
})
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => MerchantRouteRoute,
})
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => MerchantRouteRoute,
})
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => MerchantRouteRoute,
})
const MerchantRestaurantRoute = MerchantRestaurantRouteImport.update({
  id: "/restaurant",
  path: "/restaurant",
  getParentRoute: () => MerchantRouteRoute,
})
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => AdminRouteRoute,
})
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => AdminRouteRoute,
})
const AdminRestrosIndexRoute = AdminRestrosIndexRouteImport.update({
  id: "/restros/",
  path: "/restros/",
  getParentRoute: () => AdminRouteRoute,
})
const AdminRestrosRestroIdRoute = AdminRestrosRestroIdRouteImport.update({
  id: "/restros/$restroId",
  path: "/restros/$restroId",
  getParentRoute: () => AdminRouteRoute,
})
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AdminRouteRoute,
})
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => AdminRouteRoute,
})
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => CustomerRouteRoute,
})
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => CustomerRouteRoute,
})
const CustomerRestroRestroIdRoute = CustomerRestroRestroIdRouteImport.update({
  id: "/restro/$restroId",
  path: "/restro/$restroId",
  getParentRoute: () => CustomerRouteRoute,
})
const MerchantOrdersIndexRoute = MerchantOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => MerchantRouteRoute,
})
const MerchantOrdersOrderIdRoute = MerchantOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => MerchantRouteRoute,
})

const AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminRestrosRestroIdRoute: AdminRestrosRestroIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminRestrosIndexRoute: AdminRestrosIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const CustomerRouteRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerHomeRoute: CustomerHomeRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerRestroRestroIdRoute: CustomerRestroRestroIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const MerchantRouteRouteChildren = {
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantRestaurantRoute: MerchantRestaurantRoute,
  MerchantOrdersOrderIdRoute: MerchantOrdersOrderIdRoute,
  MerchantOrdersIndexRoute: MerchantOrdersIndexRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

const AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
